#postgres:
#    image: postgres:9.6
#    environment:
#        - POSTGRES_USER=mobi
#        - POSTGRES_PASSWORD=localdev
#        - POSTGRES_DB=mobi
#

dbm:
  # Keep the version consistent with RDS
  image: postgres:9.5.2
  container_name: dbm
  ports:
    # For easy data query from the host
    - 5432:5432
  volumes:
    # Persist the data to /mnt/sda1 on the docker-machine host to survive
    # `docker-compose rm` and VM restart.
    - /mnt/sda1/mobi-devdb:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: mobi
    POSTGRES_PASSWORD: localdev


webserver:
    image: mobi/airflow
    links:
        - dbm:dbm.service
    environment:
        - LOAD_EX=n
        - EXECUTOR=Local
        - AIRFLOW_POSTGRES_HOST=dbm.service
        - AIRFLOW_POSTGRES_PORT=5432
        - AIRFLOW_POSTGRES_USER=mobi
        - AIRFLOW_POSTGRES_PASSWORD=localdev
        - AIRFLOW_POSTGRES_DB=mobi
    volumes:
        - ./dags:/usr/local/airflow/dags
        - ./script/entrypoint.sh:/entrypoint.sh
        # Uncomment to include custom plugins
        # - ./plugins:/usr/local/airflow/plugins
    ports:
        - "8080:8080"
    command: webserver
